config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1:
      branch: main
      repo: https://github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-ecru-sloth.sh
        container: qc.acc_pokey-yellow-dormouse
  QC.Doc:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-olivine-bullfrog.sh
        container: qc.doc_slaphappy-viridian-opossum
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-malachite-tetra.sh
        container: qc.doc_slaphappy-smalt-caterpillar
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-green-harrier.sh
        container: qc.doc_homely-xanthic-flamingo
  QC.Lic:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-charcoal-cougar.sh
        container: qc.lic_lovely-dandelion-mayfly
  QC.Sec:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-saffron-husky.sh
        container: qc.sec_nippy-salmon-olm
  QC.Sty:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-cerise-lionfish.sh
        container: qc.sty_craggy-khaki-wolverine
  QC.Uni:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-lime-dollar.sh
        container: qc.uni_stealthy-peach-sloth
  QC.Ver:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-cream-camel.sh
        container: qc.ver_craggy-aqua-emu
timeout: 5400
