config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1:
      branch: main
      repo: https://github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-periwinkle-hippopotamus.sh
        container: qc.acc_ready-razzmatazz-monster
  QC.Doc:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-lime-millipede.sh
        container: qc.doc_surly-cyan-cuttlefish
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-tomato-retriever.sh
        container: qc.doc_muzzy-aqua-audemer
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-sepia-dollar.sh
        container: qc.doc_sickly-cardinal-oriole
  QC.Lic:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-goldenrod-cassowary.sh
        container: qc.lic_gamy-mustard-frigatebird
  QC.Met:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.homely-mustard-numbat.sh
        container: qc.met_bumpy-amaranth-badger
  QC.Sec:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-asparagus-flounder.sh
        container: qc.sec_skinny-amber-crab
  QC.Sty:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-cardinal-pinscher.sh
        container: qc.sty_baggy-magenta-mongoose
  QC.Uni:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.homey-sepia-woodlouse.sh
        container: qc.uni_nippy-gold-neanderthal
  QC.Ver:
    repos:
      github.com/norwegian-geotechnical-institute/BingCLAW_5.6.1 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-viridian-frise.sh
        container: qc.ver_randy-blue-eel
timeout: 5400
